title: Shuli Lv's Homepage
page-top-title: Shuli Lv &ensp;|&ensp;吕书礼
top-section-bg-text: Robotics
home-title: Shuli Lv &ensp;|&ensp;吕书礼
home-subtitle: Shuli Lv&ensp;|&ensp;吕书礼
copyright-text: '&copy; Shuli Lv 2023-2025. All Rights Reserved.'
ga-measurement-id: 'G-7KCQXN4PTX'
analytics-title: 'Analytics'
analytics-note: 'Google Analytics dashboard (pageviews and world regions)'
analytics-iframe-url: ''
analytics-iframe-height: '56.25%'
