title: Shuli Lv's Homepage
page-top-title: Shuli Lv &ensp;|&ensp;吕书礼
top-section-bg-text: Robotics
home-title: Shuli Lv &ensp;|&ensp;吕书礼
home-subtitle: Shuli Lv&ensp;|&ensp;吕书礼
copyright-text: '&copy; Shuli Lv 2023-2025. All Rights Reserved.'
